In [10]:
import os
import numpy as np
from tqdm import tqdm
import pandas as pd

In [11]:
NEW_EMBED_DIR = 'new_embeddings/Arabic/wav_ZHAA/'
OUTPUT_DIR = 'new_embeddings/'

In [12]:
os.system(f"ls {NEW_EMBED_DIR} | grep '\.npy$' | wc -l")

1132

0

In [13]:
data = []
labels = []
count = 0
with os.scandir(NEW_EMBED_DIR) as d:
    for e in tqdm(d):
        #print(e.name)
        if e.is_file() and e.name.endswith('.npy'):
            count += 1
            embd = np.load(f"{NEW_EMBED_DIR}/{e.name}")
            labels.append('Arabic')
            data.append(embd)
print(count)

2264it [00:00, 56813.05it/s]

1132

In [14]:
df = pd.DataFrame(data)
df_labels = pd.DataFrame(labels)

In [15]:
df

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,-0.031786,-0.032667,-0.055430,0.013281,0.022225,0.018658,-0.016245,-0.000096,-0.010357,0.011019,...,0.020916,0.015336,-0.024427,0.011272,0.006525,-0.042604,0.010256,0.046252,-0.016884,0.023690
1,-0.028257,-0.022729,-0.043663,0.000486,-0.006719,0.005212,-0.016673,-0.020378,0.011754,0.005472,...,-0.003891,0.008574,-0.019851,-0.055879,0.020112,-0.028196,-0.010360,0.037210,-0.003084,-0.005441
2,-0.029402,-0.027479,-0.013257,-0.008493,0.022677,0.009330,0.005520,-0.026070,0.019653,0.016188,...,0.012340,0.018235,-0.012167,-0.022877,0.014899,-0.010266,-0.018014,0.032390,-0.009547,0.008741
3,-0.018087,-0.020389,-0.053015,0.019175,0.007128,0.035521,-0.013282,-0.024897,0.014299,0.009660,...,0.006096,0.012331,-0.003535,-0.009353,0.031529,-0.020173,0.005787,0.021396,-0.007338,-0.001010
4,-0.022544,-0.017775,-0.034642,0.005788,0.007989,0.006143,-0.030077,-0.006426,-0.014514,-0.011155,...,-0.001208,0.019042,-0.018329,-0.011711,0.005776,-0.030782,-0.000375,0.022580,-0.000588,0.009805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127,-0.036846,-0.025505,-0.015782,-0.002398,-0.000953,0.006941,-0.017237,-0.020488,0.022241,0.011180,...,0.007413,0.028774,-0.014578,0.007244,0.024110,-0.019956,-0.006639,0.057992,0.014961,0.000071
1128,-0.017712,-0.017256,-0.031967,-0.016123,-0.004389,0.030489,-0.011386,0.011767,-0.008318,-0.020228,...,0.015026,0.002563,-0.017388,0.016136,0.010345,-0.025964,-0.023415,0.079519,0.021564,0.020351
1129,-0.046149,-0.024116,-0.016959,0.010485,0.007950,0.018662,-0.035105,-0.020141,0.000282,0.004188,...,-0.016825,0.030865,0.004329,0.017424,0.024620,-0.026779,0.004306,0.070085,0.007460,0.004521
1130,-0.034180,-0.018292,-0.022127,0.006454,0.022652,0.021148,-0.023049,-0.021304,-0.014144,0.014646,...,0.025191,0.015982,-0.009512,-0.001145,0.020556,-0.009943,0.000591,0.024065,0.015012,0.011468
1131,-0.027345,-0.027678,-0.067530,-0.005786,-0.004389,0.025632,-0.006945,-0.038824,0.009252,-0.019658,...,0.016772,0.014473,-0.013038,0.007235,0.021528,0.010478,-0.024162,0.080566,0.000737,-0.004546

In [16]:
df_labels.columns = ['Y']
df_labels

           Y
0     Arabic
1     Arabic
2     Arabic
3     Arabic
4     Arabic
...      ...
1127  Arabic
1128  Arabic
1129  Arabic
1130  Arabic
1131  Arabic

[1132 rows x 1 columns]

In [17]:
df_full = pd.concat([df, df_labels], axis=1)
df_full

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,Y
0,-0.031786,-0.032667,-0.055430,0.013281,0.022225,0.018658,-0.016245,-0.000096,-0.010357,0.011019,...,0.015336,-0.024427,0.011272,0.006525,-0.042604,0.010256,0.046252,-0.016884,0.023690,Arabic
1,-0.028257,-0.022729,-0.043663,0.000486,-0.006719,0.005212,-0.016673,-0.020378,0.011754,0.005472,...,0.008574,-0.019851,-0.055879,0.020112,-0.028196,-0.010360,0.037210,-0.003084,-0.005441,Arabic
2,-0.029402,-0.027479,-0.013257,-0.008493,0.022677,0.009330,0.005520,-0.026070,0.019653,0.016188,...,0.018235,-0.012167,-0.022877,0.014899,-0.010266,-0.018014,0.032390,-0.009547,0.008741,Arabic
3,-0.018087,-0.020389,-0.053015,0.019175,0.007128,0.035521,-0.013282,-0.024897,0.014299,0.009660,...,0.012331,-0.003535,-0.009353,0.031529,-0.020173,0.005787,0.021396,-0.007338,-0.001010,Arabic
4,-0.022544,-0.017775,-0.034642,0.005788,0.007989,0.006143,-0.030077,-0.006426,-0.014514,-0.011155,...,0.019042,-0.018329,-0.011711,0.005776,-0.030782,-0.000375,0.022580,-0.000588,0.009805,Arabic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127,-0.036846,-0.025505,-0.015782,-0.002398,-0.000953,0.006941,-0.017237,-0.020488,0.022241,0.011180,...,0.028774,-0.014578,0.007244,0.024110,-0.019956,-0.006639,0.057992,0.014961,0.000071,Arabic
1128,-0.017712,-0.017256,-0.031967,-0.016123,-0.004389,0.030489,-0.011386,0.011767,-0.008318,-0.020228,...,0.002563,-0.017388,0.016136,0.010345,-0.025964,-0.023415,0.079519,0.021564,0.020351,Arabic
1129,-0.046149,-0.024116,-0.016959,0.010485,0.007950,0.018662,-0.035105,-0.020141,0.000282,0.004188,...,0.030865,0.004329,0.017424,0.024620,-0.026779,0.004306,0.070085,0.007460,0.004521,Arabic
1130,-0.034180,-0.018292,-0.022127,0.006454,0.022652,0.021148,-0.023049,-0.021304,-0.014144,0.014646,...,0.015982,-0.009512,-0.001145,0.020556,-0.009943,0.000591,0.024065,0.015012,0.011468,Arabic
1131,-0.027345,-0.027678,-0.067530,-0.005786,-0.004389,0.025632,-0.006945,-0.038824,0.009252,-0.019658,...,0.014473,-0.013038,0.007235,0.021528,0.010478,-0.024162,0.080566,0.000737,-0.004546,Arabic

In [18]:
df_full.to_csv('embeddings/arabic2.csv')